[resources]
root = ".local"

[deno]
config = ".runseal/deno.json"
lock = ".runseal/deno.lock"
permissions = [
  "--unstable-ffi",
  "--allow-read=.",
  "--allow-write=out",
  "--allow-env=RUNSEAL_PROFILE_PATH",
  "--allow-ffi",
  "--allow-run=git,cargo,deno,flavor,sidecar,pwsh,runseal,target/debug/prototype.exe",
]

[[injections]]
type = "env"

[injections.vars]
WULIN_REPO_LOCAL_DIR = "resource://"
WULIN_REPO_SECRETS_DIR = "resource://secrets"
WULIN_REPO_TMP_DIR = "resource://tmp"
