function fail(message: string): never {
    console.error(message);
    Deno.exit(1);
}

async function run(command: string, args: string[]): Promise<string> {
    const output = await new Deno.Command(command, {
        args,
        cwd: root,
        stdout: "piped",
        stderr: "piped",
    }).output();
    if (!output.success) {
        const error = new TextDecoder().decode(output.stderr).trim();
        fail(`init: ${command} ${args.join(" ")} failed${error ? `: ${error}` : ""}`);
    }
    return new TextDecoder().decode(output.stdout).trim();
}

async function requireFile(path: string): Promise<void> {
    try {
        const info = await Deno.stat(`${root}/${path}`);
        if (!info.isFile) fail(`init: expected a file at ${path}`);
    } catch {
        fail(`init: missing required file: ${path}`);
    }
}

if (Deno.args.includes("--help") || Deno.args.includes("-h")) {
    console.log("Usage: runseal :init");
    console.log("\nValidate the canonical project surface and install repository hooks.");
    Deno.exit(0);
}
if (Deno.args.length > 0) fail(`init: unexpected argument: ${Deno.args[0]}`);

const profilePath = Deno.env.get("RUNSEAL_PROFILE_PATH");
if (!profilePath) fail("init: RUNSEAL_PROFILE_PATH is not set");
const root = profilePath.replace(/[\\/][^\\/]+$/, "");

for (
    const file of [
        "AGENTS.md",
        "README.md",
        "Cargo.lock",
        "Cargo.toml",
        "apps/prototype/Cargo.toml",
        "apps/prototype/src/actor.rs",
        "apps/prototype/src/camera.rs",
        "apps/prototype/src/object/interaction.rs",
        "apps/prototype/src/locomotion.rs",
        "apps/prototype/src/object/observation.rs",
        "apps/prototype/src/object/mod.rs",
        "apps/prototype/tests/object_observation_policy.rs",
        "apps/prototype/tests/object_interaction_policy.rs",
        "apps/prototype/tests/session_report.rs",
        "apps/prototype/src/main.rs",
        "apps/prototype/src/presentation.rs",
        "apps/prototype/src/session.rs",
        "apps/prototype/src/time.rs",
        "apps/workbench/Cargo.toml",
        "apps/workbench/src/main.rs",
        "apps/workbench/src/inspect/protocol.rs",
        "apps/workbench/src/inspect/app/actor.rs",
        "apps/workbench/src/inspect/app/objects.rs",
        "apps/workbench/src/inspect/protocol/objects.rs",
        "crates/engine-runtime/Cargo.toml",
        "crates/engine-runtime/src/lib.rs",
        "crates/engine-runtime/src/runtime/mod.rs",
        "crates/engine-runtime/src/runtime/object_query.rs",
        "crates/engine-runtime/src/runtime/actor.rs",
        "crates/engine-runtime/src/runtime/motion_batch.rs",
        "crates/engine-runtime/src/runtime/simulation_actor.rs",
        "crates/engine-runtime/src/scene/mod.rs",
        "crates/engine-runtime/src/timeline/mod.rs",
        "crates/engine-runtime/src/rendering/renderer/actor_projection.rs",
        "crates/engine-runtime/src/rendering/renderer/object_target.rs",
        "crates/engine-runtime/src/rendering/meshlet_scene/skeletal/surface/target_probe.rs",
        "crates/engine-runtime/tests/private/object_target.rs",
        "crates/engine-runtime/tests/private/surface_target.rs",
        "crates/engine-runtime/src/rendering/async_resident/renderer/query.rs",
        "crates/engine-runtime/src/rendering/composition/mod.rs",
        "crates/engine-runtime/src/rendering/meshlet_scene/skeletal/resources/mod.rs",
        "crates/engine-runtime/src/rendering/meshlet_scene/skeletal/resources/actor.rs",
        "crates/engine-runtime/src/streaming/objects/mod.rs",
        "crates/engine-runtime/src/streaming/terrain/mod.rs",
        "crates/reference-host/Cargo.toml",
        "crates/reference-host/src/activation.rs",
        "crates/reference-host/src/bootstrap.rs",
        "crates/reference-host/src/clock.rs",
        "crates/reference-host/src/input.rs",
        "crates/reference-host/src/window.rs",
        "crates/region-format/src/global.rs",
        "crates/terrain-format/src/global.rs",
        "tools/region-cooker/src/main.rs",
        "tools/terrain-cooker/src/main.rs",
        "experiments/0031-canonical-runtime-convergence/README.md",
        "experiments/0032-authored-object-presentation/README.md",
        "experiments/0033-deterministic-temporal-presentation/README.md",
        "experiments/0034-cooked-gltf-geometry/README.md",
        "experiments/0035-cooked-gltf-material/README.md",
        "experiments/0036-cooked-gltf-skeletal-animation/README.md",
        "experiments/0037-source-duration-playback/README.md",
        "experiments/0038-camera-visible-directional-shadows/README.md",
        "experiments/0039-canonical-runtime-host-separation/README.md",
        "experiments/0040-runtime-frame-transaction/README.md",
        "experiments/0041-deterministic-host-input/README.md",
        "experiments/0042-declarative-runtime-bootstrap/README.md",
        "experiments/0043-thin-prototype-host/README.md",
        "experiments/0044-exact-canonical-terrain-query/README.md",
        "experiments/0053-retained-terrain-body-lifecycle/README.md",
        "experiments/0054-transactional-retained-body-advance/README.md",
        "experiments/0055-mandatory-terrain-transaction-cleanup/README.md",
        "experiments/0056-transactional-retained-body-batch/README.md",
        "experiments/0057-transactional-simulation-body-advance/README.md",
        "experiments/0058-bounded-host-elapsed-clock/README.md",
        "experiments/0059-bounded-host-activation/README.md",
        "experiments/0060-mandatory-simulation-control-cleanup/README.md",
        "experiments/0061-composed-host-time-admission/README.md",
        "experiments/0062-prototype-body-bootstrap/README.md",
        "experiments/0063-live-prototype-time-driver/README.md",
        "experiments/0064-retained-runtime-actor-authority/README.md",
        "experiments/0065-mandatory-canonical-operator-cleanup/README.md",
        "experiments/0066-bounded-actor-render-projection/README.md",
        "experiments/0067-self-contained-visible-record/README.md",
        "experiments/0068-frame-safe-actor-gpu-admission/README.md",
        "experiments/0069-prototype-gravity-admission/README.md",
        "experiments/0070-mandatory-actor-projection-cleanup/README.md",
        "experiments/0071-actor-relative-camera-anchor/README.md",
        "experiments/0072-transactional-actor-render-admission/README.md",
        "experiments/0073-typed-actor-render-backpressure/README.md",
        "experiments/0074-prototype-horizontal-locomotion/README.md",
        "experiments/0075-mandatory-prototype-readiness-cleanup/README.md",
        "experiments/0076-prototype-traversal-activation/README.md",
        "experiments/0077-transactional-locomotion-presentation/README.md",
        "experiments/0078-committed-locomotion-facing/README.md",
        "experiments/0079-self-contained-prototype-operator/README.md",
        "experiments/0080-mandatory-live-documentation-authority-cleanup/README.md",
        "experiments/0081-actor-local-animation-epoch/README.md",
        "experiments/0082-plain-prototype-v0-stage-seal/README.md",
        "experiments/0093-exact-canonical-object-query/README.md",
        "experiments/0094-exact-canonical-object-position/README.md",
        "experiments/0095-mandatory-presentation-status-cleanup/README.md",
        "experiments/0096-exact-canonical-object-nearest/README.md",
        "experiments/0097-committed-prototype-object-observation/README.md",
        "experiments/0098-source-qualified-object-identity/README.md",
        "experiments/0099-typed-canonical-object-resolution/README.md",
        "experiments/0100-retired-standalone-terrain-contact/README.md",
        "experiments/0101-version-gated-prototype-object-target/README.md",
        "experiments/0102-frame-bound-object-target-feedback/README.md",
        "experiments/0103-committed-prototype-object-action/README.md",
        "experiments/0104-capacity-one-prototype-object-consumption/README.md",
        "experiments/0105-retired-recurring-compatibility-witness/README.md",
        "experiments/0106-committed-prototype-object-facing/README.md",
        "experiments/0107-rejected-object-action-feedback/README.md",
        "experiments/0108-bounded-prototype-session-completion/README.md",
        "experiments/0109-capacity-exhausted-object-action-feedback/README.md",
        "experiments/0110-retired-transient-object-action-report/README.md",
        "experiments/0111-native-window-close-session-completion/README.md",
        "experiments/0112-native-focus-discontinuity/README.md",
        "experiments/0113-native-jump-readmission/README.md",
        "experiments/0114-native-midair-jump-rejection/README.md",
        "experiments/0115-retired-final-unknown-event-witnesses/README.md",
        "experiments/0116-native-held-camera-repeat/README.md",
        "experiments/0117-native-out-of-range-key-rejection/README.md",
        "experiments/0118-batch-invariant-native-object-feedback/README.md",
        "experiments/0119-native-opposite-camera-edge-cancellation/README.md",
        "experiments/0120-retired-bootstrap-probes-resource-cleanup/README.md",
        "experiments/0121-native-counter-clockwise-camera-wrap/README.md",
        "experiments/0122-native-camera-repress-readmission/README.md",
        "experiments/0123-native-run-modifier-release/README.md",
        "experiments/0124-native-run-modifier-repress-readmission/README.md",
        "experiments/0125-retired-actor-velocity-compatibility-probes/README.md",
        "experiments/0126-native-opposite-locomotion-release/README.md",
        "experiments/0127-native-diagonal-walk/README.md",
        "experiments/0128-native-diagonal-run/README.md",
        "experiments/0129-post-readiness-native-object-actions/README.md",
        "experiments/0130-retired-startup-action-acceptance/README.md",
        "experiments/0131-post-readiness-finite-boundary-run/README.md",
        "assets/third-party/khronos-fox/README.md",
        "docs/adr/0035-authored-object-presentation.md",
        "docs/adr/0036-deterministic-temporal-presentation.md",
        "docs/adr/0037-cooked-gltf-geometry.md",
        "docs/adr/0038-cooked-gltf-material.md",
        "docs/adr/0039-cooked-gltf-skeletal-animation.md",
        "docs/adr/0040-source-duration-presentation-time.md",
        "docs/adr/0041-camera-visible-directional-shadows.md",
        "docs/adr/0042-canonical-runtime-host-separation.md",
        "docs/adr/0043-runtime-frame-transaction.md",
        "docs/adr/0044-normalized-host-input-journal.md",
        "docs/adr/0045-canonical-bootstrap-readiness.md",
        "docs/adr/0046-reference-platform-host.md",
        "docs/adr/0047-canonical-terrain-query.md",
        "docs/adr/0056-retained-terrain-body-lifecycle.md",
        "docs/adr/0057-transactional-retained-body-advance.md",
        "docs/adr/0058-retired-caller-owned-terrain-transactions.md",
        "docs/adr/0059-transactional-retained-body-batch.md",
        "docs/adr/0060-transactional-simulation-body-advance.md",
        "docs/adr/0061-bounded-host-elapsed-clock.md",
        "docs/adr/0062-bounded-win32-activation.md",
        "docs/adr/0063-retired-independent-simulation-controls.md",
        "docs/adr/0064-composed-host-time-admission.md",
        "docs/adr/0065-prototype-body-bootstrap.md",
        "docs/adr/0066-live-prototype-time-driver.md",
        "docs/adr/0067-retained-runtime-actor-authority.md",
        "docs/adr/0068-neutral-canonical-operator-identity.md",
        "docs/adr/0069-bounded-actor-render-projection.md",
        "docs/adr/0070-self-contained-visible-record.md",
        "docs/adr/0071-frame-safe-actor-gpu-admission.md",
        "docs/adr/0072-prototype-gravity-admission.md",
        "docs/adr/0073-retired-standalone-actor-projection.md",
        "docs/adr/0074-actor-relative-camera-mutation.md",
        "docs/adr/0075-transactional-actor-render-admission.md",
        "docs/adr/0076-typed-actor-render-backpressure.md",
        "docs/adr/0077-prototype-fixed-horizontal-locomotion.md",
        "docs/adr/0078-current-prototype-readiness-authority.md",
        "docs/adr/0079-prototype-traversal-activation.md",
        "docs/adr/0080-transactional-actor-presentation-command.md",
        "docs/adr/0081-committed-prototype-locomotion-facing.md",
        "docs/adr/0082-self-contained-prototype-operator.md",
        "docs/adr/0083-live-documentation-authority.md",
        "docs/adr/0084-actor-local-animation-epoch.md",
        "docs/adr/0085-plain-prototype-v0-stage-boundary.md",
        "docs/adr/0096-exact-canonical-object-query.md",
        "docs/adr/0097-exact-canonical-object-position.md",
        "docs/adr/0098-retired-standalone-presentation-status.md",
        "docs/adr/0099-bounded-canonical-object-nearest.md",
        "docs/adr/0100-committed-prototype-object-observation.md",
        "docs/adr/0101-source-qualified-object-identity.md",
        "docs/adr/0102-typed-canonical-object-resolution.md",
        "docs/adr/0103-retired-standalone-terrain-contact.md",
        "docs/adr/0104-version-gated-prototype-object-target.md",
        "docs/adr/0105-frame-bound-object-target-feedback.md",
        "docs/adr/0106-committed-prototype-object-action.md",
        "docs/adr/0107-capacity-one-prototype-object-consumption.md",
        "docs/adr/0108-retired-recurring-compatibility-witness.md",
        "docs/adr/0109-committed-prototype-object-facing.md",
        "docs/adr/0110-frame-bound-object-rejection-feedback.md",
        "docs/adr/0111-bounded-prototype-session-completion.md",
        "docs/adr/0112-frame-bound-capacity-exhaustion-feedback.md",
        "docs/adr/0113-retired-transient-object-action-report.md",
        "docs/adr/0114-native-window-close-session-completion.md",
        "docs/adr/0115-native-prototype-focus-discontinuity.md",
        "docs/adr/0116-native-prototype-jump-readmission.md",
        "docs/adr/0117-native-midair-jump-rejection.md",
        "docs/adr/0118-retired-final-unknown-event-witnesses.md",
        "docs/adr/0119-native-held-camera-repeat.md",
        "docs/adr/0120-native-out-of-range-key-rejection.md",
        "docs/adr/0121-batch-invariant-native-object-feedback.md",
        "docs/adr/0122-native-opposite-camera-edge-cancellation.md",
        "docs/adr/0123-retired-bootstrap-probes-resource-cleanup.md",
        "docs/adr/0124-native-counter-clockwise-camera-wrap.md",
        "docs/adr/0125-native-camera-repress-readmission.md",
        "docs/adr/0126-native-run-modifier-release.md",
        "docs/adr/0127-native-run-modifier-repress-readmission.md",
        "docs/adr/0128-retired-actor-velocity-compatibility-probes.md",
        "docs/adr/0129-native-opposite-locomotion-release.md",
        "docs/adr/0130-native-diagonal-walk.md",
        "docs/adr/0131-native-diagonal-run.md",
        "docs/adr/0132-post-readiness-native-object-actions.md",
        "docs/adr/0133-retired-startup-action-acceptance.md",
        "docs/adr/0134-post-readiness-finite-boundary-run.md",
        "flavor.toml",
        "runseal.toml",
        "sidecar.toml",
        "sidecar.benchmark.toml",
        "sidecar.bootstrap.toml",
        "sidecar.prototype.toml",
        ".runseal/deno.json",
        ".runseal/deno.lock",
        ".runseal/hooks/pre-commit",
        ".runseal/wrappers/init.ts",
        ".runseal/wrappers/guard.ts",
        ".runseal/wrappers/gpu-lab.ts",
        ".runseal/wrappers/prototype.ts",
        ".runseal/wrappers/workbench.ts",
        ".runseal/wrappers/canonical-actor.ts",
        ".runseal/wrappers/canonical-frame.ts",
        ".runseal/wrappers/canonical-prototype.ts",
        ".runseal/wrappers/canonical-resources.ts",
        ".runseal/wrappers/canonical-runtime.ts",
        ".runseal/support/canonical-frame.ts",
        ".runseal/support/canonical-runtime.ts",
        ".runseal/support/canonical-rollover.ts",
        ".runseal/support/canonical-setup.ts",
        ".runseal/support/idle-shell.ts",
        ".runseal/support/object/query.ts",
        ".runseal/support/object/nearest.ts",
        ".runseal/support/object/integration.ts",
        ".runseal/support/object/feedback.ts",
        ".runseal/support/guard/presentation-status-removal.ts",
        ".runseal/support/guard/simulation-control-removal.ts",
        ".runseal/support/guard/canonical-operator.ts",
        ".runseal/support/guard/live-operator-surface.ts",
        ".runseal/support/guard/input-journal-removal.ts",
        ".runseal/support/guard/object-identity.ts",
        ".runseal/support/guard/prototype-session.ts",
        ".runseal/support/guard/compatibility-witness-removal.ts",
        ".runseal/support/guard/terrain-transaction-removal.ts",
        ".runseal/support/runtime-bootstrap.ts",
        ".runseal/support/prototype/host.ts",
        ".runseal/support/prototype/actor.ts",
        ".runseal/support/prototype/camera_counter_clockwise.ts",
        ".runseal/support/prototype/camera_repress.ts",
        ".runseal/support/prototype/sessions/run_release.ts",
        ".runseal/support/prototype/sessions/run_repress.ts",
        ".runseal/support/prototype/sessions/locomotion_opposition.ts",
        ".runseal/support/prototype/sessions/diagonal_walk.ts",
        ".runseal/support/prototype/sessions/diagonal_run.ts",
        ".runseal/support/prototype/input/mod.ts",
        ".runseal/support/prototype/input/prepared.ts",
        ".runseal/support/prototype/input/actions.ts",
        ".runseal/support/prototype/input/sequences.ts",
        ".runseal/support/prototype/object/observation.ts",
        ".runseal/support/prototype/object/observation_order.ts",
        ".runseal/support/prototype/object/observation_test.ts",
        ".runseal/support/prototype/object/interaction.ts",
        ".runseal/support/prototype/object/gates.ts",
        ".runseal/support/prototype/sessions/focus.ts",
        ".runseal/support/prototype/sessions/gates.ts",
        ".runseal/support/prototype/sessions/mod.ts",
        ".runseal/support/prototype/presentation.ts",
        ".runseal/support/prototype/traversal.ts",
        ".runseal/support/cooked-gltf-presentation.ts",
        ".runseal/support/temporal-presentation.ts",
        ".runseal/support/terrain/query.ts",
        ".runseal/support/actor/lifecycle.ts",
        ".runseal/support/actor/admission.ts",
        ".runseal/support/actor/gpu.ts",
        ".runseal/support/actor/animation.ts",
        ".runseal/support/actor/simulation.ts",
    ]
) await requireFile(file);

console.log("==> stable toolchain");
for (
    const [tool, args] of [
        ["runseal", ["--version"]],
        ["flavor", ["--version"]],
        ["sidecar", ["--version"]],
        ["cargo", ["--version"]],
        ["deno", ["--version"]],
    ] as const
) console.log(await run(tool, [...args]));

await run("git", ["config", "core.hooksPath", ".runseal/hooks"]);
console.log(`core.hooksPath = ${await run("git", ["config", "--get", "core.hooksPath"])}`);
console.log("development environment ready");
